
import Foundation

class Konstants{
	static var IN_CART_ITEM = "IN_CART_ITEM"
	static var PRODUCT_ITEM = "PRODUCT_ITEM"
	static var SPLASH_SCREEN = "SPLASH_SCREEN"
	static var LOGIN_PAGE = "LOGIN_PAGE"
	static var REGISTRATION_PAGE = "REGISTRATION_PAGE"
	static var CHOOSE_UNI = "CHOOSE_UNI"
	static var CLIENT_LANDING_PAGE = "CLIENT_LANDING_PAGE"
	static var GURU_LANDING_PAGE = "GURU_LANDING_PAGE"
	static var PLACE_ORDER_PAGE = "PLACE_ORDER_PAGE"
	static var COMPLETE_ORDER_PAGE = "COMPLETE_PAGE"
	static var ORDER_HISTORY_PAGE = "ORDER_HISTORY_PAGE"
	static var APPLICATION_PAGE  = "APPLICATION_PAGE"
	static var GURU_ADD_TO_VENTURE_PAGE = "GURU_ADD_TO_VENTURE_PAGE"
	static var VENDORS_TAB = "VENDORS_TAB"
	static var STOCK_TAB = "STOCK_TAB"
	static var ORDER_MANAGEMENT = "ORDER_MANAGMENT"
	static var SETTINGS_PAGE  = "SETTINGS_PAGE"
}
